files:
  - source: "/content/**/**/*.[yaml/md]"
    ignore:
      - "**/collection/**/**"
      - "**/*.collection.*"
      - "**/blog/**/*.md"
    translation: /i18n/**/%file_name%.%two_letters_code%.%file_extension%
